name: Run Cypress with Custom Runner

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Base URL of the app'
        required: true
        default: 'http://localhost:2368'
      email:
        description: 'Email for login'
        required: true
      password:
        description: 'Password for login'
        required: true
      ghost_version:
        description: 'Ghost version'
        required: true
        default: '5.114.1'

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install Ghost CLI
        run: npm install -g ghost-cli

      - name: Set up Ghost instance
        run: |
          mkdir ghost-site
          cd ghost-site

          # Instalar Ghost sin auto-setup
          ghost install ${{ github.event.inputs.ghost_version }} --no-prompt --no-setup --no-start --local

          # Iniciar Ghost
          ghost start &

      - name: Wait for Ghost to be ready
        run: |
          echo "Waiting for Ghost to be ready..."
          until curl -s http://localhost:2368/ghost/ > /dev/null; do
            sleep 5
          done
          echo "Ghost is ready!"

      - name: Install Node dependencies
        run: npm ci

      - name: Run Cypress tests with custom runner
        run: |
          URL="${{ github.event.inputs.url }}" \
          GHOST_URL="${{ github.event.inputs.url }}/ghost/#" \
          GHOST_EMAIL="${{ github.event.inputs.email }}" \
          GHOST_PASSWORD="${{ github.event.inputs.password }}" \
          GHOST_VERSION="${{ github.event.inputs.ghost_version }}" \
          node cypressRunner.js

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/results/screenshots/

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: cypress/results/

      - name: Teardown Ghost
        if: always()
        run: |
          cd ghost-site
          ghost stop
          ghost uninstall --yes
          cd ..
          rm -rf ghost-site
